
clientCode=LPSD1
transUserName=Abh789@sp
transUserPassword=P8c3WQ7ei
authKey=x0xzPnXsgTq0QqXx
authIV=oLA38cwT6IYNGqb3
paymentUrl=https://stage-securepay.sabpaisa.in/SabPaisa/sabPaisaInit?v=1
txnEnquiryUrl= https://stage-sandbox.sabpaisa.in/SabPaisa/status
refundUrl= https://stage-sandbox.sabpaisa.in/SabPaisa/refund?
bankingListUrl= https://stage-sandbox.sabpaisa.in/SabPaisa/banklist
acknowledgementUrl= https://stage-sandbox.sabpaisa.in/SabPaisa/acknowledge
callbackUrl=http://localhost:8080/paymentResponse

spring.datasource.url=jdbc:mysql://localhost:3306/sab_pg_integration?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false

spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql= true




